DM-37987: Update to support python 3.11
lsst/utils pull request #145
Opened 2023-02-13 23:31 UTC by timj

## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

2023-02-21 06:53 UTC, ktlim requested changes

2023-02-21 06:53 UTC, ktlim commented on python/lsst/utils/logging.py
> +        stack_level = 2
This is the same calculation as is used to generate the default level in `LsstLoggerAdapter` (and is thus the same as returned by `LsstLoggerAdapter._process_stacklevel()` with no argument).  I think it would be better if it is unified somehow rather than duplicated.

2023-02-21 06:53 UTC, ktlim commented on python/lsst/utils/logging.py
> +        stacklevel = stacklevel + 1 if _OFFSET_STACK else stacklevel
I'd kind of like to see this `1` be an argument to `_process_stacklevel()` so that all `_OFFSET_STACK` handling can be limited to that function.

2023-02-21 06:53 UTC, ktlim commented on python/lsst/utils/logging.py
> +            stacklevel = stacklevel + kwargs.pop("stacklevel") - 1
It's not clear where the `- 1` comes from here.  Can you add a comment to clarify?

2023-02-24 02:43 UTC, ktlim approved these changes

2023-02-24 02:43 UTC, ktlim commented on python/lsst/utils/logging.py
> +        if _OFFSET_STACK:
Not sure it helps much, but this could be converted to a call to `_calculate_base_stacklevel(stacklevel, offset)`, so there's only one use of `_OFFSET_STACK`, no?

2023-02-27 20:40 UTC, timj commented on python/lsst/utils/logging.py
> +        if _OFFSET_STACK:
Yes, I should have spotted that.

2023-02-27 21:07 UTC, merged